#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/neurotools/nrn/neuron_install/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/neurotools/nrn/neuron_install/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/sabahmallick/Desktop/ProjS5/ProjectS5/Proj_S5/components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
